# Keep the serializers generated by kotlinx.serialization for the cached sign model.
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.**
-keepclassmembers class dk.gaijin.karoo.citylimit.**$$serializer { *; }
-keepclassmembers class dk.gaijin.karoo.citylimit.core.**$$serializer { *; }
